import { EventObserver } from '../EventObserver/EventObserver';
import ISliderSettings from './ISliderSettings';
declare class Model {
    private settings;
    valuesObserver: EventObserver;
    settingsObserver: EventObserver;
    constructor(settings?: object);
    setSettings(settings: object): void;
    getSettings(): ISliderSettings;
    calculateValueWithStep(pos: number[]): number[];
    calculateValueWithStep(pos: number): number;
    calculateFromPercentsToValue(curPosInPercents: number): number;
    calculateFromValueToPercents(curPosInValue: number): number;
    setCalculatedValue(curPosInPercents: number, updateObject: string): number;
    setCalculatedStartValues(): void;
    dispatchValue(): void;
    dispatchSettings(): void;
    setIsRange(tmp: boolean): void;
    setMin(tmp: number): void;
    setMax(tmp: number): void;
    setStep(tmp: number): void;
    setValue(tmp: number, currentValueNumber?: number): void;
    setValues(tmp: number[]): void;
    setOrientation(tmp: string): void;
    setHasTip(tmp: boolean): void;
    getIsRange(): boolean;
    getMin(): number;
    getMax(): number;
    getStep(): number;
    getValue(): number;
    getValues(number?: number): number[] | number;
    getOrientation(): string;
    getHasTip(): boolean;
}
export { Model };
export default Model;
